# environment.yml
# create environment with:
# $  conda env create -f environment.yml
# After creating the environment, set up for Jupyter with:
# python -m ipykernel install --user \
#    --name dissipationIFR \
#    --display-name "🌊 dissipationIFR"
name: dissipationIFR

channels:
  - conda-forge

dependencies:
  - python=3.14

  - numpy
  - scipy
  - pandas
  - xarray

  - ipython
  - ipykernel
  - ipywidgets

  - matplotlib

  - netcdf4
  - cftime

  - pyyaml
  - tqdm

  - pip

  - pytest
  - pytest-cov
  - ruff
  - mypy

  - pip:
      - gsw
      - cmocean
      - git+https://github.com/ocean-uhh/seagliderOG1.git