import cmocean.cm as cmo
import numpy as np

variables = {
    'EPSILON': {'attributes': {
        'long_name': 'Dissipation Rate of Turbulent Kinetic Energy',
        'units': 'W/kg',
        },
        'colormap': cmo.delta,
    },
    'TEMP': {'attributes': {
        'long_name': 'Temperature',
        'units': '°C',
        },
        'colormap': cmo.thermal,
    },
    'PSAL': {'attributes': {
        'long_name': 'Salinity',
        'units': 'PSU',
        },
        'colormap': cmo.haline,
    },
    'DENSITY': {'attributes': {
        'long_name': 'Density',
        'units': 'kg/m³',
        },
        'colormap': cmo.dense,
    },
    'W_MEAS': {'attributes': {
        'long_name': 'Measured Vertical Velocity',
        'units': 'cm/s',
        },
        'colormap': cmo.speed,
    },
    'W_WATER': {'attributes': {
        'long_name': 'Vertical Velocity of Water',
        'units': 'cm/s',
        },
        'colormap': cmo.speed,
    },
    'N': {'attributes': {
        'long_name': 'Brunt-Väisälä Frequency',
        'units': '1/s',
        },
        'colormap': cmo.thermal,
    },
    'N_SORTED': {'attributes': {
        'long_name': 'Sorted Brunt-Väisälä Frequency',
        'units': '1/s',
        },
        'colormap': cmo.thermal,
    },
    'SIGMA_T': {'attributes': {
        'long_name': 'Potential Density Anomaly',
        'units': 'kg/m³',
        },
        'colormap': cmo.dense,
    },
}


vars_to_keep = [
 'GLIDER_VERT_VELO_MODEL',
 'THETA',
 'TEMP',
 'GLIDE_SPEED',
 'SIGTHETA',
 'SIGMA_T',
 'PSAL',
 'PRES',
 'GLIDER_HORZ_VELO_MODEL',
 'GLIDE_ANGLE',
 'VBD',
 'ROLL',
 'PITCH',
 'HEADING',
 'CNDC',
 'BUOYANCY',
 'DIVENUM',
 'PROFILE_NUMBER',
 'DEPTH_Z',
 'SENSOR_FLUOROMETER_0000',
 'SENSOR_CTD_245201',
 'SENSOR_OXYGEN_005',
 'VBD_MIN_CNTS',
 'VBD_CNTS_PER_CC',
 'VBD_CC_PER_CNTS',
 'MASS',
 'VOLMAX',
 'C_VBD',
 'HD_A',
 'HD_B',
 'HD_C',
 'PLATFORM_SERIAL_NUMBER',
 'PLATFORM_MODEL',
 'TRAJECTORY',
 'DEPLOYMENT_LATITUDE',
 'DEPLOYMENT_LONGITUDE',
 'DEPLOYMENT_TIME',]